### PR TITLE
Made changes in SearchDialog to resolve the form dialog issue.

### PR DESCRIPTION
**Pull request by Ath47**
Here are the changes which I made -
1. Now the Search Dialog will automatically close once you select a city.
2. Change environment variables name from OPENWEATHER_API_KEY to REACT_APP_WEATHER_Key since it's a good practice to prefix react env variables with REACT_APP_.
3. Changed cursor-default to cursor-pointer on mouse hover on the suggestions to enhance UX.

### CODE REVIEW

**Comment by patthoege** [comment]
Thank you for the updates! 

I’ve tested the changes, and everything is working smoothly. It is a great improvement for the user experience. Changing the environment variable naming is also a smart move 😎
Thanks again for your contributions to the project ^^

**Comment by Ath47** [comment]
Actually I wanted to give you few more feedbacks on improvements and user enhancements.
So if you are up for it, I would contribute to the project further more.

**Comment by patthoege** [comment]
I'm glad that you're interested to contribute further. I'd love to hear your feedback on improvements and user enhancements 

To help us manage and prioritize the work effectively, could you create user stories for each of the enhancements you'd like to propose?

**Comment by Ath47** [comment]
Sure
Actually there are few bugs which should be fixed and few enhancements I want to propose.

**Pull request merged**
